### ISSUE TITLE
Index per tenant

### ISSUE THREAD

**Issue by janwout** [django-es/django-elasticsearch-dsl#234]
We are using django_tenants for multi-tenancy and want to use django-elasticsearch-dsl. Is it possible to use management command search_index --rebuild with an argument, which decides what index is going to be rebuild? Or something like this. So you set the index name from the management command?

And use something like this: ```python manage.py tenant_command search_index --rebuild --schema=site4```

**Comment by safwanrahman** [comment]
Thanks for the issue, It is possible to mention the models [as per the documentation](https://django-elasticsearch-dsl.readthedocs.io/en/latest/management.html)

Can you explain more about the usecase? I do not have any idea about `multi-tenancy`

**Comment by janwout** [comment]
@safwanrahman thank you for the response. We implemented django-tenants, so we have for each client a database schema. We can use a specific database schema with a django-tenants management command, see below.

The use case is, that we want to have an index in elasticsearch for each client. So if the index could be added as an argument to the management commands of django-elasticsearch-dsl, this could be a solution for us. What do you think?

```
python manage.py tenant_command search_index --rebuild --schema=client1 
```

**Comment by janwout** [comment]
I think in short, add the possibility to add index as an argument to the management commands

Is this possible you think @safwanrahman

**Comment by riyaadmiller** [comment]
@safwanrahman Hi, any update on this? Have you managed to update this to support schema level indexing?

**Comment by sanderlepik** [comment]
Any updates on this? @safwanrahman @janwout

**Comment by saurabhsalgia** [comment]
> @safwanrahman thank you for the response. We implemented django-tenants, so we have for each client a database schema. We can use a specific database schema with a django-tenants management command, see below.
> 
> The use case is, that we want to have an index in elasticsearch for each client. So if the index could be added as an argument to the management commands of django-elasticsearch-dsl, this could be a solution for us. What do you think?
> 
> ```
> python manage.py tenant_command search_index --rebuild --schema=client1 
> ```

Hi...Did u get any solution for this?

**Comment by Adityakeskar** [comment]
Hi ... Has anyone come up with a solution to this? My use case is also the same.

```
python manage.py tenant_command search_index --rebuild --schema=client1 
```

**Comment by janwout** [comment]
@Adityakeskar @saurabhsalgia @sanderlepik we added tenant_name to all documents: https://gitlab.com/pleio/backend2/-/blob/dev/core/documents.py#L30

So not an index per tenant, but the tenant info in each document. We use this tenant_name field when searching
