### ISSUE TITLE
New data and populate command

### ISSUE THREAD

**Issue by psilva1982** [django-es/django-elasticsearch-dsl#280]
I started using elastic search with django. I have a legacy system that inserts data into the database. To index the data I used the populate command. If the legacy system inserts new data into the database, can I use the populate command again to index only that new data or do I need to rebuild every new load of data from that legacy system in the database?

**Comment by aaronn** [comment]
I have the same question. Does the populate command only index new data?

**Comment by alexgarel** [comment]
> Does the populate command only index new data?

No for there is no universal easy way to know which data has changed or is new.

But you can easily write your own command to do it based on your data (maybe you would reindex data modified or created since last indexing, if you store modification / creation date).

**Comment by safwanrahman** [comment]
Thanks @alexgarel for the answer.
