### ISSUE TITLE
Best practice to convert dict to nested or object

### ISSUE THREAD

**Issue by pythonBerg** [django-es/django-elasticsearch-dsl#282]
I have a document class where many of the attributes are derived from an external class called "annotation". If a document has an address, its because someone annotated this document with "address".

In order the represent this in a flat elasticsearch doc, I want to store both the value of the annotation and the id of the annotation object. This way, I can reintegrate search results to display the document and annotation. Currently, the getAttribute(xxx) returns a simple dict: {'value': '2 main st', 'source':'223421'}. How can I represent this as nested field. I am assigning 'attr=' to the method that returns the dict. How do I access dict contents using keys to populate "properties"?

Any guidance appreciated.

**Comment by alexgarel** [comment]
This is not the right place to ask such questions, please post on stackoverflow using appropriate tags.

However, you should have a method `prepare_xxxx(sejf, obj)` that return the list of dict for nested field.

**Comment by alexgarel** [comment]
see https://django-elasticsearch-dsl.readthedocs.io/en/latest/fields.html#using-prepare-field
