### ISSUE TITLE
add index: not_analyzed to a field

### ISSUE THREAD

**Issue by illiteratewriter** [django-es/django-elasticsearch-dsl#287]
I know this is not a place to ask a question, but my question in SO went unanswered. I am a newb with Python, Django and Elasticsearch. I wanted to do a search for full sentence and I figured out I have to add `index: not_analyzed` to get that result. But I am unsure how to add it.

```
@registry.register_document
class FieldDocument(Document):
  class Index:
    name = "fields"

  class Django:
    model = Fields
    fields = [
      'title'
    ]
```

This is my code, how should I add `index: not_analysed` to title? Also can I get an example on how to add that to NestedField?

I think it would be greater if there is docs about that..

**Comment by alexgarel** [comment]
From elasticsearch 5, you should choose between [keyword](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html) (not analyzed) or [Text](https://www.elastic.co/guide/en/elasticsearch/reference/current/text.html)

In your case you can do it so:

```python
from django_elasticsearch_dsl import fields

@registry.register_document
class FieldDocument(Document):

  title = fields.KeywordField()

  class Index:
    name = "fields"

  class Django:
    model = Fields
    fields = [
      'title'
    ]
```

Note that you could also make two fields : one analyzed and the other not like so:

```python
    title = fields.TextField({'raw': KeywordField()})
```

You can then, query on `title.raw` (or `title__raw=` in a filter).

Also remember to read the docs : https://django-elasticsearch-dsl.readthedocs.io/en/latest/fields.html

**Comment by illiteratewriter** [comment]
@alexgarel thank you for the reply. I actually read the docs, but couldn't understand it. 

When running the code provided above, I am getting the following error:
```
django_elasticsearch_dsl.exceptions.RedeclaredFieldError: You cannot redeclare the field named 'title' on FieldDocument
```

**Comment by illiteratewriter** [comment]
Hey, there's a small change in the above code, I think when you add `title = fields.KeywordField()` you don't need to add `'title'` in the Django class fields.

```
from django_elasticsearch_dsl import fields

@registry.register_document
class FieldDocument(Document):

  title = fields.KeywordField()

  class Index:
    name = "fields"

  class Django:
    model = Fields
    fields = []  # <== title removed from here
```

Leaving it here in case it helps someone else also.

**Comment by alexgarel** [comment]
yes, sorry, I forgot to remove the `fields = ["title"]` ! You got it :-)

The usage of `field = ['foo', 'bar']` is just some kind of shortcut when you want the library too choose the default fields for you.

We may update the doc to be more clear. Pull Request to the documentation is always welcome. When one discovers a library he may easily see what needs to be ugraded in the docs for new comers !

**Comment by illiteratewriter** [comment]
@alexgarel just an update, I wanted to add case-insensitivity also to the search, so I changed `title=fields.KeywordField` to `title=fields.TextField` and added a custom analyzer on it. Thank you for taking the time to point me in the right direction with the word `Keyword` :-) I will try to do a P.R. as soon as possible.
