### ISSUE TITLE
Unable create geo-point

### ISSUE THREAD

**Issue by zhuyuanmao** [django-es/django-elasticsearch-dsl#291]
Hi

I just create geo-point following below

models.py
```python
class Property(models.Model):
'''
'''   utilities_included =ArrayField(
          models.CharField(max_length=255,blank=True)
      ) 
      latitude= models.DecimalField(null=True,
                               blank=True,
                               decimal_places=15,
                               max_digits=19,
                               default=0)
     longitude= models.DecimalField(null=True,
                                    blank=True,
                                    decimal_places=15,
                                    max_digits=19,
                                    default=0)
     @property
     def location(self):
          return [self.longitude, self.latitude]
 
```
documents.py

```python
@INDEX.doc_type
@registry.register_document
class PropertyDocument(Document):
    # Location
    location = fields.GeoPointField(lat_lon=True)
    utilities_included = fields.KeywordField(multi=True)
    class Django:
        model = Property # The model associated with this Document
       
    class Meta(object):
        parallel_indexing = True
        queryset_pagination = 50  # This will split the queryset
                                  # into parts while indexing
 
```
After creating index on Elasticsearch, I can't find the type of location. the mapping is 
<img width="345" alt="Screen Shot 2020-08-22 at 7 58 29 PM" src="https://user-images.githubusercontent.com/32859592/90969104-dc06d100-e4b1-11ea-9ada-a84ec3db7ee4.png">

I tried to implement search query with GeoPoint and received error:
```python
def geo_search(lat, lng, distance):
    q = Q('geo_distance', distance='{}km'.format(distance), location=[lng, lat])
    s = PropertyDocument.search()
    s = s.query(q)

    response = s.execute()
    print(response)

```
```
RequestError(400, 'search_phase_execution_exception', 'field [location] is not a geo_point field')
```

It seems it can't get the type of geo_point. Can anyone give me ideas regarding this?

**Comment by safwanrahman** [comment]
Seems to be solved. thanks for providing the feedback.

**Comment by millerf** [comment]
@safwanrahman I had the same issue and lost 3 days figuring out what was happening. I even opened [an issue in django-elasticsearch-dsl-drf](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/issues/300).

I think this is troubling enough to be escalated as a bug, don't you think? Beasically GeoPoints mappings are replaced with `{"properties":{"lat":{"type":"float"},"lon":{"type":"float"}}` unless index is rebuild. This is extremely annoying. 

Any lead on how to fix that?
