### ISSUE TITLE
populating problem: single index + base-inherited, multiple documents

### ISSUE THREAD

**Issue by knno** [django-es/django-elasticsearch-dsl#293]
Hello thanks for the package..
I am using a single index for two documents inherited from a basedocument.
The future plan is to use a multilingual search (index-per-language)

Trying to use a custom document base for models Page and Category.
The problem is that when indexing.. I think in Elasticsearch index they are overlapping/overwritten.
(Because sometimes when using `python manage.py search_index --rebuild` and the output is changed, there are different indexed results... but the hits count is the same, 3).
For example, if indexing of categories occurs before page, one of the categories will be missing from index.

##### documents.py
```py
from elasticsearch_dsl.index import Index
from django_elasticsearch_dsl import fields
from django_elasticsearch_dsl.registries import registry
from django_elasticsearch_dsl import Document, fields
from .models import (Category, Page)

index = Index('django')

class BaseDocument(Document):
    text = fields.TextField()

@registry.register_document
@index.document
class CategoryDocument(BaseDocument):
    class Django:
        model = Category


@registry.register_document
@index.document
class PageDocument(BaseDocument):
    class Django:
        model = Page
        fields = [
            'created_on',
            'updated_on',
        ]
```

##### Command
```bash
$ python manage.py search_index --rebuild
```
##### Output
```
Are you sure you want to delete the 'django' indexes? [y/N]: y
Deleting index 'django'
Creating index 'django'
Indexing 1 'Page' objects 
Indexing 3 'Category' objects
```

##### Command
```bash
$ curl -X GET "127.0.0.1:9200/django/_search?pretty&q=*:*"
```
##### Output
```json
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 3,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "django",
        "_type" : "_doc",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "text" : "I am a Category\n",
        }
      },
      {
        "_index" : "django",
        "_type" : "_doc",
        "_id" : "2",
        "_score" : 1.0,
        "_source" : {
          "text" : "I am a Category\n",
        }
      },
      {
        "_index" : "django",
        "_type" : "_doc",
        "_id" : "3",
        "_score" : 1.0,
        "_source" : {
          "text" : "I am a Category\n",
        }
      }
    ]
  }
}
```

As you can see it's 3 items whereas the indexed objects are 4! Also, as I mentioned the hits are changed when the populating is changed (which occurs).

Could you please help me? Any suggestions or if I'm doing something wrong?

**Comment by solace** [comment]
@knno Hi, how did you resolve this?

**Comment by knno** [comment]
@solace Hello :D I closed this issue since I think you can't use a single index.

##### You can't make a single index for all the model. :/

## How I managed languages?
By using a function `prepare_text` in `BaseDocument` class. It just renders a django template file.
I use the text field for search, it holds model class in addition to some translatable fields.

##### page_text.txt
```txt
{{ object.name_en }}
{{ object.name_ar }}

category
صنف تصنيف

{{ object.slug }}
{{ object.description_en }}
{{ object.description_ar }}
```

Finally I complete-load the object from the django databases by its ID and class.

**Comment by solace** [comment]
@knno I came to the same conclusion as well. Just wasn't sure if I missed something. Thanks for replying!
