### ISSUE TITLE
Data is stored in Elasticsearch AND sqlite3 database

### ISSUE THREAD

**Issue by debusgregor** [django-es/django-elasticsearch-dsl#299]
I have set up a django app which stores data into Elasticsearch. Everything works, but if I take a look into the sqlite database, the same data is stored twice. It can be found in Elasticsearch and the sqlite database. Is there a way to prevent this and only store data in Elasticsearch?

**Comment by alexgarel** [comment]
Django elasticsearch DSL is meant to do that. Both container have different use in the same application. Elasticsearch is better used for full text searches and aggregations (but not relational data), while database is efficient for relational requests (merging data together based on conditions).

If you really intend to only store data in Elasticsearch then you'd better use something like elasticsearch_dsl, but Django will get a lot in your way (there is no more real benefits to using Django over eg. Flask). 

If you're not sure, just keep database and Elasticsearch, making the database your primary source of trust (you can regenerate the elasticsearch data at will from it).
