### ISSUE TITLE
No way to update connection's http_auth

### ISSUE THREAD

**Issue by kurtwheeler** [django-es/django-elasticsearch-dsl#300]
AWS's authorization credentials expire. Therefore when I initialize my ELASTICSEARCH settings like so:
```python
    ELASTICSEARCH_DSL = {
        "default": {
            "hosts": os.getenv("ELASTICSEARCH_HOST", "elasticsearch"),
            "port": 443,
            "use_ssl": True,
            "http_auth": aws_auth,
            "connection_class": RequestsHttpConnection,
        }
    }
```

after a while, I start to get error message about how I'm unauthorized because my credentials have expired.

I need to run a function like:
```python
def update_AWS_ES_auth():
    credentials = boto3.Session().get_credentials()
    aws_auth = AWS4Auth(
        credentials.access_key,
        credentials.secret_key,
        "us-east-1",
        "es",
        session_token=credentials.token,
    )
    connections._conns["default"].transport.get_connection().session.auth = aws_auth
```

How can I make this happen either:
* whenever requests to ES start to fail because the authorization has expired
* every X amount of time, and then I can set X to be lower than the expiration time.

Any ideas of how I can accomplish this? I think the ideal way would be to be able to pass in a `refresh_http_auth_function` or something to the ES DSL settings like so:
```python
    def get_aws_auth():
        credentials = boto3.Session().get_credentials()
        aws_auth = AWS4Auth(
            credentials.access_key,
            credentials.secret_key,
            "us-east-1",
            "es",
            session_token=credentials.token,
        )
        return aws_auth

    ELASTICSEARCH_DSL = {
        "default": {
            "hosts": os.getenv("ELASTICSEARCH_HOST", "elasticsearch"),
            "port": 443,
            "use_ssl": True,
            "http_auth": aws_auth,
            "refresh_http_auth_function": get_aws_auth,
            "connection_class": RequestsHttpConnection,
        }
    }
```

which would then just be used when my credentials expiring begin to cause errors.

**Comment by safwanrahman** [comment]
I think this issue should be handeled by the parent package `elasticsearch-dsl`. So you should create a issue at https://github.com/elastic/elasticsearch-dsl-py/issues

**Comment by kurtwheeler** [comment]
Hmm, do you think you could help me figure out what it is I'd be asking that repo for? What does django-elasticsearch-dsl do with the dict that gets passed in as `ELASTICSERCH_DSL`? Does it just pass them through to an `Elasticsearch` constructor from https://github.com/elastic/elasticsearch-py? If so would that not be a more appropriate place to create an issue?

**Comment by kurtwheeler** [comment]
Hello! I would still love some guidance on how to ask for help with this issue. The relationship between django-elasticsearch-dsl, elasticsearch-dsl-py, and elasticsearch-py is pretty opaque. As an end-user, I just know there's one config I'm supposed to pass and it's the one for this project. It's not clear to me what I should even be asking about in an issue in https://github.com/elastic/elasticsearch-dsl-py/issues. It's not like I can ask them to modify the parameters to the `ELASTICSEARCH_DSL` config for this project.

**Comment by kujtimiihoxha** [comment]
@kurtwheeler I know this is an old issue but I wanted to share a solution that worked for me, basically you just implement your own ConnectionClass
```python
import boto3
from elasticsearch import RequestsHttpConnection
from requests_aws4auth import AWS4Auth


class AWSHttpConnection(RequestsHttpConnection):
    def perform_request(
        self, method, url, params=None, body=None, timeout=None, ignore=(), headers=None
    ):
        region = "us-east-1"
        service = "es"
        credentials = boto3.Session().get_credentials()
        awsauth = AWS4Auth(
            credentials.access_key,
            credentials.secret_key,
            region,
            service,
            session_token=credentials.token,
        )
        if awsauth is not None:
            self.session.auth = awsauth
        return super().perform_request(
            method, url, params, body, timeout, ignore, headers
        )

```

And use it in your configurations

```python
ELASTICSEARCH_DSL = {
    "default": {
        "hosts": f"{host}:443",
        "use_ssl": True,
        "verify_certs": True,
        "connection_class": AWSHttpConnection,
    },
}
```

**Comment by kurtwheeler** [comment]
Woah that looks great! I'll make an issue to get this implemented into my projects at some point.

Thanks for posting this!
