### ISSUE TITLE
Multiple analyzers for multi-language support

### ISSUE THREAD

**Issue by Akiat** [django-es/django-elasticsearch-dsl#309]
First of all, thank you for this great package.

I'm in a situation where I need to implement a search for multiple language for a same field.

```
class Media(models.Model):
    language = models.ForeignKey('MediaLanguage', on_delete=models.SET_NULL, to_field="code", default="en", null=True)
    keywords = TaggableManager()
```

Is it possible to define the analyzer based on the given language ? Something like this:

```
@registry.register_document
class MediaDocument(Document):
    language = fields.TextField(attr="language.code")
    if language == "fr":
        lang = "french"
    else:
        lang = "english"

    keywords = fields.TextField(analyzer=lang, attr="keywords_string") 
```

Or maybe it's possible to define multiple analyzers and to specify the one to use in query ?

Thanks a lot for your time.

**Comment by safwanrahman** [comment]
@Akiat You can not use multiple analyzer for same field in Elasticsearch. To have the feature, you can have different index for different locale or you can you [multi field functionality](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html#_multi_fields)

**Comment by Akiat** [comment]
Thanks for your answer 👍
