### ISSUE TITLE
RequestError(400, 'search_phase_execution_exception', 'failed to create query: For input string: "car"')

### ISSUE THREAD

**Issue by Murugaraju** [django-es/django-elasticsearch-dsl#312]
I am using django-elasticsearch-dsl latest, which is giving error on  multi match query, as attached image. Please mimic the same using cloning the code from https://github.com/Murugaraju/ElasticSearchMock
![elasticsearch_dsl_issue](https://user-images.githubusercontent.com/32738182/101270121-00a26280-379c-11eb-81f0-9096cebc1ba7.JPG)

**Comment by Murugaraju** [comment]
Sorry, found the solution, it is happend because searching value is string and comparing with int type made this issue.

**Comment by Murugaraju** [comment]
Sorry, found the solution, it is happend because searching value is string and comparing with int type made this issue.

**Comment by HakanPuente** [comment]
@Murugaraju How to solve , could you share your code details

**Comment by HakanPuente** [comment]
@Murugaraju How to solve , could you share your code details

**Comment by HakanPuente** [comment]
@Murugaraju how did you solve, could you share the solving part of the code.

**Comment by Murugaraju** [comment]
@HakanPuente , I just removed the field id, which is int. So it worked for me. fields=['name','color']

**Comment by Anshuman265** [comment]
@Murugaraju  Can you please point out the file in which was causing this error ? I am facing a similar issue but I am not able to fix it . Thank you

**Comment by caeser1996** [comment]
Any luck so far when I am searching with less key word its working fine but as soon as we search with multiple keywords its returning the error.
