### ISSUE TITLE
How to rename fields 

### ISSUE THREAD

**Issue by afr-dt** [django-es/django-elasticsearch-dsl#320]
How to rename fields 

Example: 
Django field

```birth_date = models.DateField()```

To elasticsearch_dsl

Here rename to camelCase

```birthDate = fields.DateField()```

**Comment by juanpsenn** [comment]
You should use `attr` inside DateField()

`birthDate = fields.DateField(attr='birth_date')`

I suggest you to ask this kind of questions in stackoverflow. Hope this helps you!

**Comment by afr-dt** [comment]
It's works, thanks
