### ISSUE TITLE
Do not update doc some fields if related model is updated

### ISSUE THREAD

**Issue by zeitler** [django-es/django-elasticsearch-dsl#359]
Hi 

Having:
class User(models.Model):
  name = models.Charfield()

class Task(models.Model):
  name = models.Charfield()
  members = models.ManyToManyField(User)

class UserDocument(Document):
  name = fields.TextField()
  age = fields.IntegerField()
  
  class Django:
    model = User

class TaskDocument(Document):
  name = fields.TexstField()
  timestamp = fields.FloatField()
  members = fields.NestedField(properties={'name': fields.TextField()})

  class Django:
    model = Task
    related_models = [User]

  def prepare_timestamp(self, obj):
    return time.time()

Doing this:
user = Account.objects.get(id=1)
user.name = 'New name'
user.save()

django_elasticsearch will update UserDocument as expected, and also TaskDocument.
The thing is, I only want to update TaskDocument.members. And not the TaskDocument fields.

Meaning that timestamp will always be updated, and I want that field only be updated when Task itself is changed.

Any way to achieve this?

Also, is there a way to specify that User.age is changed, do not trigger TaskDocument or UserDocument update?

Kind regards,

Emanuel

**Comment by saadmk11** [comment]
> Meaning that timestamp will always be updated, and I want that field only be updated when Task itself is changed.

The simplest solution here maybe adding a timestamp filed on the Task Model itself and indexing that, which will make the timestamp persistent with the Task itself.

You can see the related issue here https://github.com/django-es/django-elasticsearch-dsl/issues/277 for updating specific fields using this package.

**Comment by zeitler** [comment]
Hi

Thanks for your answer.

It was exacly what I've done.

I've also tried using what you suggest in #277, but specifing only certains fields, other fields got blank.

Perhaps was my mistake, but I went in another direction,

Thank you

kind regards, 
Emanuel

**Comment by konman1989** [comment]
@saadmk11 any updates on this issue? Is this possible to ignore some fields in a related model on a Django signal?
