### ISSUE TITLE
Index is not created

### ISSUE THREAD

**Issue by moritzteichner** [django-es/django-elasticsearch-dsl#360]
Hello there,
I am trying to work with your libary but the search_index --rebuild command is not working for me.
I do not get an error but the index i am trying to create is not being created at all.
Can you provide a solution to my problem?

**Comment by saadmk11** [comment]
Have you registered the documents to the registry that you want to index?
for example:

```python
@registry.register_document
class CarDocument(Document):
    ...
```

A code sample would be useful to debug this issue.

**Comment by moritzteichner** [comment]
Sorry, already solved it. Thanks anyway :)
