### ISSUE TITLE
System out of memory on  indexing

### ISSUE THREAD

**Issue by mathijsfr** [django-es/django-elasticsearch-dsl#383]
I need to reindex 22million docs. However, my system crashes due to not having enough ram. I have about 10gb of ram available. How can I solve this?

command:
`python manage.py search_index --rebuild --model <model>`

settings used:
```
ELASTICSEARCH_DSL_PARALLEL = True
ELASTICSEARCH_DSL_AUTO_REFRESH = False

  class Meta:
        parallel_indexing = True
        queryset_pagination = 50
```

Edit:
System also goes out of memory on no parallel indexing

**Comment by safwanrahman** [comment]
@mathijsfr You need to add `queryset_pagination` in `class Django` as you can see in the [doc](https://django-elasticsearch-dsl.readthedocs.io/en/latest/quickstart.html?highlight=queryset_pagination#declare-data-to-index) to get actual benefit.

**Comment by mathijsfr** [comment]
@safwanrahman My system still went out of memory after doing that. I have written my own code to do `self.django.model._default_manager.all()` in chunks to fix the problem.

queryset_pagination in Django didn't fix my error. Also, isn't the default for queryset_pagination 500?

**Comment by safwanrahman** [comment]
@mathijsfr What code did you write to solve the issue? can you share?
