### ISSUE TITLE
Duplicate items stored in ES

### ISSUE THREAD

**Issue by yatahaze** [django-es/django-elasticsearch-dsl#401]
I'm using this to index a database of products. For some reason some of our products are duplicating. Everything on the Django side is only there once, but on the ES side of things they're duplicated.

Am I missing some sort of primary key setting on our Document or something. What should I be looking for to solve this?

If you need more details I can provide. Our document code is rather long so I opted to not include it yet.

**Comment by alexgarel** [comment]
The most common case is that your Elasticsearch documents, prepared for indexing, do not have an id. In such case, ES creates a random id for them. Next time, when you index your document, it attributes a new id, and so you have double entries.

Look at [DocType.generate_id)[https://github.com/django-es/django-elasticsearch-dsl/blob/master/django_elasticsearch_dsl/documents.py#L173] by default it use `pk` but you may have to overload it in your case.

**Comment by yatahaze** [comment]
This is true! Also it seems to have been an issue on one deployment due to me changing an ID but forgetting to fully wipe the index first. Case closed!
