### ISSUE TITLE
Is this library still maintained ?

### ISSUE THREAD

**Issue by MajesticOl** [django-es/django-elasticsearch-dsl#418]
Hello !

It seems like there is no support (as of now) for the current Elasticsearch versions 8.X which has been released around February 2022.(half a year ago)

My questions is if this library is still maintained ? Are there any plans to update to Elasticsearch 8.X ?
Depending on this answer my company will decide to use the library or not. 

Thanks and best regards !

**Comment by safwanrahman** [comment]
@MajesticOl This library is still maintained. If your company is using it in production and will decide according to it, I would be happy review patch with Elasticsearch 8.x support from any of the team member of your company. Let me know if your company is willing to allocate resource for that, I will spare some time for review and merge with priority. 🤩

**Comment by salcedo** [comment]
7.x will be End of Life upon the release of 9.x. We use this library in production but do not have the human resources to devote to patching at this time.

https://www.elastic.co/support/eol

**Comment by DarkAbhi** [comment]
There's an update to elastic DSL to support v8 officially. This should help ? @safwanrahman 
https://github.com/elastic/elasticsearch-dsl-py/issues/1569#issuecomment-1697828868

**Comment by safwanrahman** [comment]
It looks interesting! Thanks @DarkAbhi

**Comment by DarkAbhi** [comment]
ES DSL 8.9.0 is out. 

https://github.com/elastic/elasticsearch-dsl-py/issues/1569#issuecomment-1709882640

**Comment by DarkAbhi** [comment]
This issue can be closed @safwanrahman

**Comment by safwanrahman** [comment]
Yes. Thanks @DarkAbhi
