### ISSUE TITLE
[Question] conditional logic from another index

### ISSUE THREAD

**Issue by scheung38** [django-es/django-elasticsearch-dsl#432]
I have two indices: Address and Reserved:

I have a flag from one index, Address called kind_of_address which is either 'k' - known or 'u' - unknown that is determined from another index list of Reserved addresses. What is the logic to do that please?

model.py
```
class Address(model.Models):
     STATUS = Choices('u', 'k')
     kind_of_address = models.CharField(max_length=1, choices=STATUS, default=STATUS.k)

class Reserved(models.Model):
    Address_1 = models.CharField(max_length=35, blank=True, help_text="Address_1") ## say post code W1 3RS
```

If user makes a query in the search bar and it is not one of reserved addresses then it is the default  value or else
changes on the fly to the opposite value.
     
![Screenshot 2022-11-07 at 15 22 21](https://user-images.githubusercontent.com/1273014/200347401-47d19503-c766-4ff2-b664-24ad52787dcc.png)

**Comment by safwanrahman** [comment]
It would be better to post this question in stackoverflow.

**Comment by scheung38** [comment]
But this is specific to Django Elasticsearch
